dbt metrics coalesce update
HousewareHQ/dbt_segment_metrics pull request #9
Opened 2022-10-13 09:46 UTC by AryanMadhavVerma

- update metric definition with compatible syntax
- update packages file to include dbt metrics v1.3

2022-10-18 04:05 UTC, nipunj15 requested changes

2022-10-18 04:05 UTC, nipunj15 commented on models/metrics/event_counts/daily/metrics.yml
> +- name: segment__daily_event_count_by_event_calculation_method
Extra change, pls remove

2022-10-18 07:06 UTC, AryanMadhavVerma commented on models/metrics/event_counts/daily/metrics.yml
> +- name: segment__daily_event_count_by_event_calculation_method
I've made changes. Please check

2022-10-27 06:48 UTC, nipunj15 approved these changes

2022-10-27 07:19 UTC, merged